import Head from 'next/head'


export default function Home() {
    return (
      <div>
        <Head>
          <title>HOME d| Kumi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  sadasdasdas
    
  
  
      </div>
    )
  }
  