import Head from 'next/head'
import Image from 'next/image'

import Nav from '../components/en/homepage/nav'
import Heroes from '../components/en/homepage/heroes'
import Product from '../components/en/homepage/product'
import Review from '../components/en/homepage/review'

export default function Home() {
  return (
    <div>
      <Head>
        <title>HOME | Kumi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <Heroes />

      <br /><br />

      <Product />

      <Review />


    </div>
  )
}
